### ISSUE TITLE
Got SafeMode when use simple player

### ISSUE THREAD

**Issue by sking512** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#12]
Device: iPhoneX 12.1.2 rootlessjb
Set SimplePlayer work on old version 1.0.3.
Got SafeMode when 1.0.3 later

**Comment by KpwnZ** [comment]
Do you have crash log please?

**Comment by KpwnZ** [comment]
I think I have fixed the problem, beta version will be available soon. Sorry for the inconvenience.

**Comment by sking512** [comment]
I'm so sorry about dump crash log on rootlessJB

**Comment by KpwnZ** [comment]
A new version has been submitted.

**Comment by sking512** [comment]
same problem...on new version (1.2.1)
I try use cr4shed dump log, but that is not working !

**Comment by sking512** [comment]
I tried to use the old version of Cr4shed to dump logs。
================================================
Date: 2019-11-25 15:14:48 +0000
Bundle id: com.apple.springboard
Exception type: NSInvalidArgumentException
Reason: -[MediaControlsContainerView transportStackView]: unrecognized selector sent to instance 0x158018e30
Parent symbol: CoreFoundation - 0x000000021201a7dc <redacted> + 1412
=================================================

**Comment by KpwnZ** [comment]
Please add my beta repo and I will upload beta version there. Thanks for your help.

**Comment by sking512** [comment]
Thank your help, the Simple Player is work.
But it still has a little problem, It can't show control media when respring, then it becomes normal when I switch songs.
![BF71071F-5BA5-41E1-B900-1910C43A0CC5](https://user-images.githubusercontent.com/57693254/69598146-6285a380-1043-11ea-836e-05372b07e4ee.gif)

**Comment by KpwnZ** [comment]
This problem seems to be fixed in the latest beta, I will close this issue. If you have more question, please open a new one.
