### ISSUE TITLE
SimpleLS 2 on iOS 13.2.2 drain battery an cpu load 100 % and more..checkra1n 0.95

### ISSUE THREAD

**Issue by marijandj** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#14]
SimpleLS2 drain battery and cpu load 100 % (Appconduitd load cpu 98 %) on iOS13.2.2 jailbreak checkra1n 0.9.5.After remove SimpleLS2 cpu load 5-7 % and battery drain is normally.

**Comment by KpwnZ** [comment]
When AOD is on the device will drain battery faster than lock screen, especially LCD devices. I recommend only use AOD when charging. I am also trying to find a better way to improve the battery life. Sorry for the inconvenience.
