### ISSUE TITLE
SimpleLS 2 v1.2.1 drain battery and high load cpu

### ISSUE THREAD

**Issue by marijandj** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#17]
SimpleLS 2 v1.2.1 on iphone 7 iOS 13.2.2 checkra1n 0.9.5 drain battery fast and high load cpu 100% and more......please fix

**Comment by KpwnZ** [comment]
Which app did you use to check CPU load? And LCD device will drain battery a lot then other devices.

**Comment by KpwnZ** [comment]
I will close another same issue.

**Comment by enaloha** [comment]
You can use System Status for CPU usage: https://apps.apple.com/us/app/system-status-hw-monitor/id407752428

I have an iPhone 7 albeit on 12.4 and don't see any issues, but obviously, I would not dream of always on features. I really don't see a problem other than user error.

**Comment by marijandj** [comment]
I use CocoaTop v2.0.2 and when install SimpleLS 2 v1.2.1 in CocoaTop in command line "appconduitd" drain cpu with 110 % - 183 % max and phone is very hoot.
I remove SimpleLS 2 from phone everything is back normal.
![IMG_0324](https://user-images.githubusercontent.com/36161086/69494178-ac8e4e00-0eb8-11ea-8428-afaa64f8d2a8.PNG)

**Comment by marijandj** [comment]
I use CocoaTop v2.0.2  when i install SimpleLS 2 v1.2.1 in CocoaTop process "appconduitd" use cpu over 170% and phone is very hot all time.
Remove from phone SimpleLS 2 everything back  to normal.
Iphone 7 iOS 13.2.2 and checkra1n v0.9.5.....use system restore and only install SimpleLS 2..cpu 170% and phone is very hott....battery drain very fast.
![IMG_0324](https://user-images.githubusercontent.com/36161086/69494299-30950580-0eba-11ea-8f77-7336b00b2f23.PNG)

**Comment by enaloha** [comment]
Here is my report:

![IMG_5A6402BF25F0-1](https://user-images.githubusercontent.com/13284542/69498311-b4cf9480-0e8a-11ea-8c59-78de3895e7ce.jpeg)


Well, I did the same and I do not see this problem on my iPhone 7. You may have some kind of conflict going on? I would suggest you use Filza to diable everything except LS2 and then gradually re-enable your other utilities.

**Comment by marijandj** [comment]
You use iOS 12.4 i am on iOS 13.2.2 big difference.I did a restore and just installed SimpleLS 2 and I get a lot of CPU usage and the battery runs out fast

**Comment by KpwnZ** [comment]
OK I will try to get an iOS 13.2 device to test it.

**Comment by KpwnZ** [comment]
Do you have Apple Watch? I found this process has something to do with Apple Watch. And I also found another user who have Apple Watch also meet the same problem.

**Comment by marijandj** [comment]
Apple Watch series 1 :-(

**Comment by KpwnZ** [comment]
Could you please try changing the AOD style from “Watch” to “SimpleLS” then check the process? I have no Apple Watch so it’s as little bit difficult to debug this problem. Sorry for the inconvenience.

**Comment by KpwnZ** [comment]
I have uploaded  a new beta version to my beta repo.

**Comment by enaloha** [comment]
what is the repo URL? KpwnZ.github.io/Cydia doesn't load in Sileo

**Comment by marijandj** [comment]
I change in "Always On Display" to "SimpleLS" instead "Watch" and my cpu in iphone 7 is 4,6 %.....
![IMG_0017](https://user-images.githubusercontent.com/36161086/69918083-13d67000-146e-11ea-947d-753d591c8a12.PNG)
![IMG_0026](https://user-images.githubusercontent.com/36161086/69918085-189b2400-146e-11ea-84bc-deba348c523b.PNG)

Thanks KpwnZ

**Comment by KpwnZ** [comment]
I bought a S1 and I think I have found the problem now, update will come after I finish my exam.

**Comment by KpwnZ** [comment]
It seems that I already fixed the bug, the high CPU load of appconduitd disappeared, and it just need a little bit clean up now.

**Comment by KpwnZ** [comment]
SimpleLS 2 1.2.3-b2 fixed the problem. And rebooting then re-jailbreaking are required to make it fully functional. I will close this issue.
