### ISSUE TITLE
No display when locked

### ISSUE THREAD

**Issue by safre19** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#19]
I just updated on iOS 13.3 and now when my phone is on the Lockscreen and it isn't unlocked with FaceID, the clock and weather won't show. It shows only after FaceID has unlocked the device. 

There is also nothing displaying when the  screen is closed and Always on is turned on.
It was working on ios 12.4

Thanks

**Comment by KpwnZ** [comment]
Yes I noticed that. New version is coming soon, you can add my beta repo to get the new version.

**Comment by KpwnZ** [comment]
Could you please try the latest version(1.2.3-b3)? I think this problem has been solved.

**Comment by KpwnZ** [comment]
I will close this issue, if you have more question, please open a new one.

**Comment by safre19** [comment]
Whats your beta repo?

Thanks
Sam.

Le 16 déc. 2019 à 20:31, KpwnZ <notifications@github.com> a écrit :

﻿

Could you please try the latest version(1.2.3-b3)? I think this problem has been solved.

**Comment by KpwnZ** [comment]
KpwnZ.github.io/Cydia

**Comment by KpwnZ** [comment]
I will close this issue since the problem was fixed.
