### ISSUE TITLE
Artsy support

### ISSUE THREAD

**Issue by fuzepod** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#2]
There is a compatibility issue with Artsy where a song change requires unlocking and locking a couple times to set the new song album color for the clock/date. I think an option to just use the default colors would work because Artsy works with most lock screen tweaks by default but may have issue with SimpleLS2 because it is also trying to change the clock color.

**Comment by KpwnZ** [comment]
Thanks for your support, will add it in beta3.

**Comment by KpwnZ** [comment]
It has been fixed now, Artsy color will be display first.

**Comment by fuzepod** [comment]
Awesome, I hope colorflow support will come soon too!
