### ISSUE TITLE
Complications tweak support

### ISSUE THREAD

**Issue by wickdj** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#20]
Hi! Can You support the tweak called Complications? Because the lock screen notifications showing under the tweak itself. Thanks for Your work!
![B425D625-B685-4673-903B-BD4FBA47E9C8](https://user-images.githubusercontent.com/25718249/71119037-8454ef00-21d9-11ea-9ec5-d83c85c366a5.png)

**Comment by KpwnZ** [comment]
I will add another option for user to customize the offset for notifications list. So that we can adapt to many lock screen tweak easily.

**Comment by KpwnZ** [comment]
In the latest version, there is an option called "Default notification center" which allow other tweak to modify the notification center offset. If this is enabled, then you can edit the value in Complications' settings to make it fit into SimpleLS 2 layout.
