### ISSUE TITLE
Two Lock Icons on screen

### ISSUE THREAD

**Issue by srdtrk** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#24]
This issue came up with the latest version. One small icon beside the Day text as intended, the other larger lock icon centered where it would be without the tweak. This also intersects with the seconds' clock (which is how I like to use the tweak) and it looks very bad. iPhone XS Max, iOS 12.1.2.
![1745830315](https://user-images.githubusercontent.com/59252793/71474538-d1fcc900-2790-11ea-9678-b4590264421a.jpg)

**Comment by KpwnZ** [comment]
Try switch between different option in SimpleLS 2 -> clock view appearance -> position of lock icon.

**Comment by KpwnZ** [comment]
Fixed in new version, will close this issue.
