### ISSUE TITLE
Two clocks. Only happens after unlocked.

### ISSUE THREAD

**Issue by Wamy-Dev** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#26]
![DCF51DE6-6002-4F5D-BE0A-069872D2E4C3](https://user-images.githubusercontent.com/25761442/71539876-a00e7280-2908-11ea-9591-8dda4866b41c.jpeg)

**Comment by KpwnZ** [comment]
More information please. Which version are you using and do you have other lock screen tweaks installed?

**Comment by WamyPlayz** [comment]
I have no other lock screen tweaks installed. It was just happening. It is fine when I first unlock my phone after it is turned off, but once it is unlocked, it has 2 clocks like my screenshot. I am using the latest version of SimpleLs2

**Comment by WamyPlayz** [comment]
No other tweaks installed. Latest version of simplels2.

**Comment by Silentassassin22** [comment]
I'm having the same issue. IOS 13.2.2
