### ISSUE TITLE
v1.3.0 Wrong order of widgets 

### ISSUE THREAD

**Issue by enaloha** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#28]
Really, really nice release. Love it. Just a minor hickup: It seems like the widget labels have been mixed up. The sunrise/sunset should be in position 2. So the current displayed labels are:

- [ ] 1. Weather 2. Step Count 3. Activity Ring 4. Sunrise/Sunset but they actually enable:
- [ ] 1. Weather 2. Sunrise/Sunset 3. Activity Ring 4. Step Count

**Comment by KpwnZ** [comment]
Fixed in 1.3.1-1, will be available later.
