### ISSUE TITLE
‘Date options’ header is DATA_OPTIONS

### ISSUE THREAD

**Issue by clubby789** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#29]
When opening the ‘Date options’ settings menu, the header reads DATA_OPTIONS.

iOS 12.4
Version 1.3.1

**Comment by enaloha** [comment]
This is now fixed in 1.3.1-2. When looking at the other headers, maybe one could also name them in a similar manner: "Select Widgets", "Widget Options", and "Always On Display"
