### ISSUE TITLE
Unexpected crashing

### ISSUE THREAD

**Issue by tlahique** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#4]
If I start playing music and put the phone to sleep, it immediately crashes.

This was on an iPhone 7 running iOS 12.1.1 jailbroken with Chimera. The music was played using spotify and I tried putting the phone to sleep using the power button as well as activator actions. The issue persisted until I uninstalled this tweak. I reinstalled and the issue reappered. Sad to see I’ll have to go without the tweak, at least for the time being.

**Comment by anon270** [comment]
This is happening to me as well on an XR jail broken on IOS 12.1.2. Such a great tweak but my phone crashes while I’m playing music on Apple Music and I go to lock the screen. It makes me respring every single time I do that.

**Comment by KpwnZ** [comment]
Since this problem has been fixed in latest version (tested by other users), I will close the issue, please contact me if there is any other problem.
