### ISSUE TITLE
Original Time won’t go away

### ISSUE THREAD

**Issue by doriankrazy** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#5]
The original IOS time & date won’t go away so there’s two times overlapping & it’s ugly & annoying .. any fix ?

**Comment by TheLastMillennial** [comment]
I also have this problem. Disabling other tweaks doesn't seem to fix it.
I've got a iPhone X running iOS 12.1.2 and jailbroke using Chimera.
I've really been enjoying this tweak and would appreciate it if you could look into this!

**Comment by KpwnZ** [comment]
This can be caused by other tweaks, I think the latest SimpleLS has already fixed it.

**Comment by TheLastMillennial** [comment]
I don't know what tweak could cause this, but it's still broken for me even on the latest release. The information I provided earlier still applies to my current device.

**Comment by KpwnZ** [comment]
> I don't know what tweak could cause this, but it's still broken for me even on the latest release. The information I provided earlier still applies to my current device.

Could you please send me your tweak list?

**Comment by TheLastMillennial** [comment]
Oh I'm dumb, I think the culprit for me was the tweak Six. I had it installed but disabled so I forgot to check if it was an issue. Turns out it was, Simple LS is working just fine for me now!
