### ISSUE TITLE
Bricks jailbreak after download. 

### ISSUE THREAD

**Issue by linus-jansson** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#59]
When installing the tweak. The phone goes black and returns to non-jailbroken state. When trying to jailbreak again the phone goes into a boot loop.

**Comment by KpwnZ** [comment]
There may be some conflicts. Could you please attach some crash logs?

**Comment by linus-jansson** [comment]
How do I do that when non-jailbroken? isn’t crash ligs locked from the end user in normal Ios?

**Comment by KpwnZ** [comment]
Maybe you can disable tweak injection then jailbreak and install crash report or Cr4shed. Then enable tweak injection again.
