### ISSUE TITLE
Safe mode

### ISSUE THREAD

**Issue by daonedw** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#6]
New update forces my A12 Xs max iOS 12.4 Unc0ver b3 into safe mode and won’t stop until I downgrade

**Comment by naaliikeoni** [comment]
Im also having safe mode issues when upgrading. Have to downgrade to get out of safe mode

**Comment by KpwnZ** [comment]
Could you please provide me more details such as crash log (Can be generated by CrashReporter or Cr4shed) Sorry for the inconvenience.

**Comment by naaliikeoni** [comment]
{"blame":[],"app_name":"ReportCrash","timestamp":"2019-11-02 07:45:15.80 -0500","app_version":"","slice_uuid":"509f1fd3-449b-30fe-968a-b23216027e16","build_version":"","share_with_app_devs":false,"is_first_party":true,"bug_type":"109","os_version":"iPhone OS 12.4 (16G77)","incident_id":"AE51CF26-135A-4CF4-9725-6DDABBDBB6E9","name":"ReportCrash","symbolicated":true}
Incident Identifier: AE51CF26-135A-4CF4-9725-6DDABBDBB6E9
CrashReporter Key:   2d373cf096eddc144e35232a4126e78b2467fcf3
Hardware Model:      iPhone11,6
Process:             ReportCrash [11903]
Path:                /System/Library/CoreServices/ReportCrash
Identifier:          ReportCrash
Version:             ???
Code Type:           ARM-64 (Native)
Role:                Unspecified
Parent Process:      launchd [1]
Coalition:           com.apple.ReportCrash [280]


Date/Time:           2019-11-02 07:45:15.7343 -0500
Launch Time:         2019-11-02 07:45:05.3806 -0500
OS Version:          iPhone OS 12.4 (16G77)
Baseband Version:    1.06.02
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4297228288
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                 0000000100228000-0000000100250000 [  160K] r-x/r-x SM=COW  ...s/ReportCrash

Triggered by Thread:  3

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0:
0       libsystem_kernel.dylib        	0x19f8253f0 0x19f801000 + 0x243f0
1       libsystem_c.dylib             	0x19f79bd00 0x19f725000 + 0x76d00
2       libsystem_c.dylib             	0x19f79baf0 0x19f725000 + 0x76af0
3       ReportCrash                   	0x100238adc 0x100228000 + 0x10adc
4       libdyld.dylib                 	0x19f6d8fd8 0x19f6d8000 + 0xfd8 

Thread 1:
0       libsystem_pthread.dylib       	0x19f8a3dc0 0x19f89a000 + 0x9dc0

Thread 2:
0       libsystem_pthread.dylib       	0x19f8a3dc0 0x19f89a000 + 0x9dc0

Thread 3 Crashed:
0       libdyld.dylib                 	0x19f6dfbdc 0x19f6d8000 + 0x7bdc
1       libdyld.dylib                 	0x19f6dfbd0 0x19f6d8000 + 0x7bd0
2       libdyld.dylib                 	0x19f6dde60 0x19f6d8000 + 0x5e60
3       libdyld.dylib                 	0x19f6ded10 0x19f6d8000 + 0x6d10
4       libdyld.dylib                 	0x19f6de890 0x19f6d8000 + 0x6890
5       libdyld.dylib                 	0x19f6dde60 0x19f6d8000 + 0x5e60
6       libdyld.dylib                 	0x19f6de834 0x19f6d8000 + 0x6834
7       CoreSymbolication             	0x1adf97924 0x1adf32000 + 0x65924
8       CoreSymbolication             	0x1adf94de4 0x1adf32000 + 0x62de4
9       Symbolication                 	0x1b77966b0 0x1b776a000 + 0x2c6b0
10      Symbolication                 	0x1b77975b4 0x1b776a000 + 0x2d5b4
11      ReportCrash                   	0x100230234 0x100228000 + 0x8234
12      ReportCrash                   	0x10022d7c8 0x100228000 + 0x57c8
13      ReportCrash                   	0x10022e804 0x100228000 + 0x6804
14      ReportCrash                   	0x100238264 0x100228000 + 0x10264
15      ReportCrash                   	0x10023b5fc 0x100228000 + 0x135fc
16      ReportCrash                   	0x10023b698 0x100228000 + 0x13698
17      libsystem_kernel.dylib        	0x19f81971c 0x19f801000 + 0x1871c
18      ReportCrash                   	0x100237c20 0x100228000 + 0xfc20
19      libsystem_pthread.dylib       	0x19f89b908 0x19f89a000 + 0x1908
20      libsystem_pthread.dylib       	0x19f89b864 0x19f89a000 + 0x1864
21      libsystem_pthread.dylib       	0x19f8a3dcc 0x19f89a000 + 0x9dcc

Thread 4:
0       libsystem_kernel.dylib        	0x19f819c60 0x19f801000 + 0x18c60
1       libsystem_kernel.dylib        	0x19f8190e8 0x19f801000 + 0x180e8
2       libsystem_kernel.dylib        	0x19f819650 0x19f801000 + 0x18650
3       ReportCrash                   	0x100237c20 0x100228000 + 0xfc20
4       libsystem_pthread.dylib       	0x19f89b908 0x19f89a000 + 0x1908
5       libsystem_pthread.dylib       	0x19f89b864 0x19f89a000 + 0x1864
6       libsystem_pthread.dylib       	0x19f8a3dcc 0x19f89a000 + 0x9dcc

Thread 3 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x00000001004b8000   x2: 0x0000000000004000   x3: 0x000000019f898de9
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000001   x7: 0x0000000000000000
    x8: 0x000000019f6fd000   x9: 0x00000001d9fa8260  x10: 0xfffffffffffffd18  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000031  x14: 0x0000000000000e29  x15: 0x0000000002020900
   x16: 0xfffffffffffffff4  x17: 0x00000001d08de658  x18: 0x0000000000000000  x19: 0x000000016fe024e8
   x20: 0x00000001004b26a0  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x00000001004ac0a0
   x24: 0x0000000000091240  x25: 0x000000016fe02528  x26: 0x00000001004ac000  x27: 0x00000000000001f5
   x28: 0x00000000000001f6   fp: 0x000000016fe02490   lr: 0x001078819f6dfbd0
    sp: 0x000000016fe02440   pc: 0x000000019f6dfbdc cpsr: 0x20000000

Binary Images (dpkg):
0x100264000 - 0x100277fff + substitute-inserter.dylib arm64e  <9b7ea35252003198bb419cca58308b9b> /usr/lib/substitute-inserter.dylib {"install_date":"2019-10-26 22:45:08 -0500","name":"Substitute Support Package","identifier":"science.xnu.substituted","version":"0.1~b1"}
0x1002cc000 - 0x1002d7fff + substitute-loader.dylib arm64e  <12942f5764e43c3f8c323403fa4b2dc0> /usr/lib/substitute-loader.dylib {"install_date":"2019-10-23 21:57:24 -0500","name":"Substitute","identifier":"com.ex.substitute","version":"0.0.14"}
0x1002e8000 - 0x1002effff + libsubstrate.dylib arm64e  <936c96041a66367aabf6053ccca5d497> /usr/lib/libsubstrate.dylib {"install_date":"2019-10-23 21:57:24 -0500","name":"Substitute","identifier":"com.ex.substitute","version":"0.0.14"}
0x1002f8000 - 0x100313fff + libsubstitute.0.dylib arm64e  <9740b355967d33648bef7fdc84d86d76> /usr/lib/libsubstitute.0.dylib {"install_date":"2019-10-23 21:57:24 -0500","name":"Substitute","identifier":"com.ex.substitute","version":"0.0.14"}
0x100434000 - 0x10043ffff + RocketBootstrap.dylib arm64e  <905a436997ad3d70950a87934aeba491> /Library/MobileSubstrate/DynamicLibraries/RocketBootstrap.dylib {"install_date":"2019-09-25 18:07:48 -0500","name":"RocketBootstrap","identifier":"com.rpetrich.rocketbootstrap","version":"1.0.7~beta3"}

Binary Images (App Store):

Binary Images (Other):
0x100228000 - 0x10024ffff   ReportCrash arm64e  <509f1fd3449b30fe968ab23216027e16> /System/Library/CoreServices/ReportCrash
0x100370000 - 0x1003cbfff   dyld arm64e  <802cc393e12634718d93864f212680a4> /usr/lib/dyld
0x19ee23000 - 0x19ee24fff   libSystem.B.dylib arm64e  <8c964dcb9a1435b38d622950e7a412f6> /usr/lib/libSystem.B.dylib
0x19ee25000 - 0x19ee7dfff   libc++.1.dylib arm64e  <d4063e21f493336286465788ebae505b> /usr/lib/libc++.1.dylib
0x19ee7e000 - 0x19ee91fff   libc++abi.dylib arm64e  <7c824a7ad71b3c368ab16c7ece88e15e> /usr/lib/libc++abi.dylib
0x19ee92000 - 0x19f619fff   libobjc.A.dylib arm64e  <e8055992eb2530e0b15a82af9bd334e4> /usr/lib/libobjc.A.dylib
0x19f61a000 - 0x19f61efff   libcache.dylib arm64e  <e7f774b5f94c35bca2e209117f6c6f80> /usr/lib/system/libcache.dylib
0x19f61f000 - 0x19f62afff   libcommonCrypto.dylib arm64e  <23637b31c4a13122b0b8e881766db89e> /usr/lib/system/libcommonCrypto.dylib
0x19f62b000 - 0x19f62efff   libcompiler_rt.dylib arm64e  <4a6a8c9a64773fcfaadf87f7ea372fd1> /usr/lib/system/libcompiler_rt.dylib
0x19f62f000 - 0x19f637fff   libcopyfile.dylib arm64e  <8039305e9f733efc9567b5ec638fe57f> /usr/lib/system/libcopyfile.dylib
0x19f638000 - 0x19f69cfff   libcorecrypto.dylib arm64e  <a8fc7d6fefc43f669a2cae628cbcadaa> /usr/lib/system/libcorecrypto.dylib
0x19f69d000 - 0x19f6d7fff   libdispatch.dylib arm64e  <9bd843073b6a3b55af071d3566e62949> /usr/lib/system/libdispatch.dylib
0x19f6d8000 - 0x19f702fff   libdyld.dylib arm64e  <5666efd3f0dd3b1cae0b0fac7e92121c> /usr/lib/system/libdyld.dylib
0x19f703000 - 0x19f703fff   liblaunch.dylib arm64e  <1fba029148b43d50890e5de9087a9e14> /usr/lib/system/liblaunch.dylib
0x19f704000 - 0x19f709fff   libmacho.dylib arm64e  <54bfbb1b83dc32eea96366055f020f07> /usr/lib/system/libmacho.dylib
0x19f70a000 - 0x19f70bfff   libremovefile.dylib arm64e  <40bcfa0769003519bd1f7da26c112023> /usr/lib/system/libremovefile.dylib
0x19f70c000 - 0x19f723fff   libsystem_asl.dylib arm64e  <c2a7888285e23e23bd13b5a94995fb0c> /usr/lib/system/libsystem_asl.dylib
0x19f724000 - 0x19f724fff   libsystem_blocks.dylib arm64e  <736168c0cbc137c695962e4deb6c0543> /usr/lib/system/libsystem_blocks.dylib
0x19f725000 - 0x19f7a4fff   libsystem_c.dylib arm64e  <75ac4c9d5bee3060b6da8cfa1bddb2a2> /usr/lib/system/libsystem_c.dylib
0x19f7a5000 - 0x19f7a9fff   libsystem_configuration.dylib arm64e  <bc625f9a899e3ebfba226be50a6b6ca4> /usr/lib/system/libsystem_configuration.dylib
0x19f7aa000 - 0x19f7b0fff   libsystem_containermanager.dylib arm64e  <d18cb9ebd5303cca8e1e14a515d877b7> /usr/lib/system/libsystem_containermanager.dylib
0x19f7b1000 - 0x19f7b2fff   libsystem_coreservices.dylib arm64e  <786f52436b513c9bb8d381dbf84eda2c> /usr/lib/system/libsystem_coreservices.dylib
0x19f7b3000 - 0x19f7b9fff   libsystem_darwin.dylib arm64e  <92172b82e4ec34f1a526d6cf5bdae0a5> /usr/lib/system/libsystem_darwin.dylib
0x19f7ba000 - 0x19f7c0fff   libsystem_dnssd.dylib arm64e  <88f2520e57cb379c99df505d24152464> /usr/lib/system/libsystem_dnssd.dylib
0x19f7c1000 - 0x19f800fff   libsystem_info.dylib arm64e  <c7024de6155d3494a730f7fe5cfe7a83> /usr/lib/system/libsystem_info.dylib
0x19f801000 - 0x19f82cfff   libsystem_kernel.dylib arm64e  <f2a2738e22e8381ebef30a0556212114> /usr/lib/system/libsystem_kernel.dylib
0x19f82d000 - 0x19f85afff   libsystem_m.dylib arm64e  <4e6f0320da2039aa88a45474adf9aa25> /usr/lib/system/libsystem_m.dylib
0x19f85b000 - 0x19f87ffff   libsystem_malloc.dylib arm64e  <44a074204d4e36059619a2cc9df7b204> /usr/lib/system/libsystem_malloc.dylib
0x19f880000 - 0x19f88bfff   libsystem_networkextension.dylib arm64e  <9c80d51b6b6e31b5aa6016daf0924624> /usr/lib/system/libsystem_networkextension.dylib
0x19f88c000 - 0x19f892fff   libsystem_notify.dylib arm64e  <2da4348cf18a3b97a2cbd802839cdf9d> /usr/lib/system/libsystem_notify.dylib
0x19f893000 - 0x19f899fff   libsystem_platform.dylib arm64e  <b809eb906d86395b818f7cafcfb764d8> /usr/lib/system/libsystem_platform.dylib
0x19f89a000 - 0x19f8a4fff   libsystem_pthread.dylib arm64e  <829ee40698373e81aab436c9f70b6726> /usr/lib/system/libsystem_pthread.dylib
0x19f8a5000 - 0x19f8a7fff   libsystem_sandbox.dylib arm64e  <29b696d8fced3d2794a19e0f0109a0b3> /usr/lib/system/libsystem_sandbox.dylib
0x19f8a8000 - 0x19f8affff   libsystem_symptoms.dylib arm64e  <8c3aca466aa53a0a850e724e407e7305> /usr/lib/system/libsystem_symptoms.dylib
0x19f8b0000 - 0x19f8c4fff   libsystem_trace.dylib arm64e  <65151ab3122439489b4b6024484d2fe0> /usr/lib/system/libsystem_trace.dylib
0x19f8c5000 - 0x19f8cafff   libunwind.dylib arm64e  <252dce3fa8f63521a43d40a1fc51a4f8> /usr/lib/system/libunwind.dylib
0x19f8cb000 - 0x19f8f9fff   libxpc.dylib arm64e  <fb445b1a85353d0ab7fe63e2ba533553> /usr/lib/system/libxpc.dylib
0x19f8fa000 - 0x19fb62fff   libicucore.A.dylib arm64e  <97eee2de71c5371eb1e5dc3d9a142da4> /usr/lib/libicucore.A.dylib
0x19fb63000 - 0x19fb74fff   libz.1.dylib arm64e  <d682fa2534c5323cb381671a6a57b6f8> /usr/lib/libz.1.dylib
0x19fb75000 - 0x19fed8fff   CoreFoundation arm64e  <23157e07bf733823ba6d1816915ffece> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x19fed9000 - 0x19fee9fff   libbsm.0.dylib arm64e  <aa07524e9de839e8bf5c7aa288151a71> /usr/lib/libbsm.0.dylib
0x19feea000 - 0x19feeafff   libenergytrace.dylib arm64e  <3a39bb95080836c895e79a0e0828a62b> /usr/lib/libenergytrace.dylib
0x19feeb000 - 0x19ff7bfff   IOKit arm64e  <a058f46d14163efd9a9103fc3ccb404a> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x19ff7c000 - 0x1a0066fff   libxml2.2.dylib arm64e  <bb961564beae38e0b41204158d8840f2> /usr/lib/libxml2.2.dylib
0x1a0067000 - 0x1a0074fff   libbz2.1.0.dylib arm64e  <acf8d6ac354b3b878df95aa9cdb4cb16> /usr/lib/libbz2.1.0.dylib
0x1a0075000 - 0x1a008dfff   liblzma.5.dylib arm64e  <6516c42e1ea1328f814285253e7357aa> /usr/lib/liblzma.5.dylib
0x1a008e000 - 0x1a0207fff   libsqlite3.dylib arm64e  <b5b4b1f691fb3ca891d06f245a3036eb> /usr/lib/libsqlite3.dylib
0x1a0208000 - 0x1a023dfff   libMobileGestalt.dylib arm64e  <c152ba19947631d799de9824256e437e> /usr/lib/libMobileGestalt.dylib
0x1a023e000 - 0x1a05f5fff   CFNetwork arm64e  <7bac5947136d32178a2c8ba7bb9ed387> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
0x1a05f6000 - 0x1a08f0fff   Foundation arm64e  <fc334924845d3e44a4aab11d9af6cdef> /System/Library/Frameworks/Foundation.framework/Foundation
0x1a08f1000 - 0x1a0a07fff   Security arm64e  <0f262a3d95d436ec88c0330791cdf46e> /System/Library/Frameworks/Security.framework/Security
0x1a0a08000 - 0x1a0a71fff   SystemConfiguration arm64e  <acee4279b4cb3b0e833e2679b9146f9c> /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
0x1a0a72000 - 0x1a0aa4fff   libCRFSuite.dylib arm64e  <3722583ea27137f7bb2c8921db2f1bd3> /usr/lib/libCRFSuite.dylib
0x1a0aa5000 - 0x1a0abbfff   libapple_nghttp2.dylib arm64e  <57bb3ef0ecfd3e1c8ffb9e1b26eadb58> /usr/lib/libapple_nghttp2.dylib
0x1a0abc000 - 0x1a0ae5fff   libarchive.2.dylib arm64e  <c8dba8a058583e6da6bde2eac60df62e> /usr/lib/libarchive.2.dylib
0x1a0baf000 - 0x1a0bc5fff   libcoretls.dylib arm64e  <e9c64531bb9a3a1599599856ec31b29d> /usr/lib/libcoretls.dylib
0x1a0bc6000 - 0x1a0bc7fff   libcoretls_cfhelpers.dylib arm64e  <662ef556b2b63b0b9ad62a070c97fe46> /usr/lib/libcoretls_cfhelpers.dylib
0x1a0bc8000 - 0x1a0bc9fff   liblangid.dylib arm64e  <bc67a1a2bd2a351aba8ad21929516d52> /usr/lib/liblangid.dylib
0x1a0bca000 - 0x1a0f3ffff   libnetwork.dylib arm64e  <2ff76d0761b334e388292f05d5d5d4f1> /usr/lib/libnetwork.dylib
0x1a0f40000 - 0x1a0f79fff   libpcap.A.dylib arm64e  <de784b132bc13022976fdba010f02216> /usr/lib/libpcap.A.dylib
0x1a0fd8000 - 0x1a0fe4fff   IOSurface arm64e  <b6e5148fc1d53f0e9ee73b5ff1fa9564> /System/Library/Frameworks/IOSurface.framework/IOSurface
0x1a1e66000 - 0x1a1e66fff   MobileCoreServices arm64e  <7229b97b51143028bcfa1cff570cda2d> /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
0x1a2522000 - 0x1a253afff   CrashReporterSupport arm64e  <9cc15d781f20331cb5f6180c0d15de8d> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/CrashReporterSupport
0x1a253b000 - 0x1a2540fff   AggregateDictionary arm64e  <eaaf29c59af73b5589a7ec2eac824066> /System/Library/PrivateFrameworks/AggregateDictionary.framework/AggregateDictionary
0x1adf32000 - 0x1adfb5fff   CoreSymbolication arm64e  <4b33d74dee233114a799315f883f056f> /System/Library/PrivateFrameworks/CoreSymbolication.framework/CoreSymbolication
0x1ae8e9000 - 0x1ae8effff   MobileSystemServices arm64e  <e699fe0cc0a63955a980f4064b27ceb1> /System/Library/PrivateFrameworks/MobileSystemServices.framework/MobileSystemServices
0x1b13d8000 - 0x1b13fcfff   MobileInstallation arm64e  <fcd4b6371f0b3c7e8d7dfef31bbe667d> /System/Library/PrivateFrameworks/MobileInstallation.framework/MobileInstallation
0x1b776a000 - 0x1b77f3fff   Symbolication arm64e  <96ddb9f2e695383aafc4a9db2ec39cb1> /System/Library/PrivateFrameworks/Symbolication.framework/Symbolication
0x1c8f84000 - 0x1c90c7fff   CoreServices arm64e  <3a9d5d1c76b33e8b87830b591d9b3e1b> /System/Library/Frameworks/CoreServices.framework/CoreServices

**Comment by naaliikeoni** [comment]
I sent you a copy and paste of the log. Let me know if that doesn’t work and I’ll try to forward it to you

**Comment by KpwnZ** [comment]
> I sent you a copy and paste of the log. Let me know if that doesn’t work and I’ll try to forward it to you
> […](#)
> Sent from my iPhone
> On Nov 2, 2019, at 11:23 AM, KpwnZ ***@***.***> wrote: Could you please provide me more details such as crash log (Can be generated by CrashReporter or Cr4shed) Sorry for the inconvenience. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Hmm... The crash process should be "SpringBoard" not "ReportCrash".

**Comment by naaliikeoni** [comment]
Is it something I’m doing or a tweak I have already?

**Comment by KpwnZ** [comment]
> Is it something I’m doing or a tweak I have already?
> […](#)

Hmm... After some testing, I think I have found the problem, but I have no A12 devices. I will try to fix it as soon as possible.

**Comment by daonedw** [comment]
I don’t know how to do that I’m sorry I’ll just stay on the downgraded one I tried upgrading and kept restarting after I was in safe mode but crash reporter didn’t post anything

**Comment by daonedw** [comment]
If you fix what you found I’ll upgrade it and tell you if it works

**Comment by daonedw** [comment]
Whatever you changed it fixed it. It now works great on A12 12.4 thank you love your tweaks
