### ISSUE TITLE
Safe mode on A12 12.4 

### ISSUE THREAD

**Issue by naaliikeoni** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#7]
Xs Max on 12.4. Worked flawless until newest upgrade. Throws me in safe mode. Had to downgrade to get out of safe mode

**Comment by KpwnZ** [comment]
Could you please provide me more details such as crash log? I don’t have A12 devices sorry.

**Comment by daonedw** [comment]
New update works good now thank you 😊
