### ISSUE TITLE
IOS14 Support?

### ISSUE THREAD

**Issue by Stonemage** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#72]
Hey XCXiao!
It doesn't appear that IOS14 is supported in SimpleLS 2. I have recently uplifted my iPhone X to 14.3 due to the new JB being out, and SimpleLS 2 is not working at all.

Any chance we might be able to get a version bump with support, please? 😊 

Thanks!

**Comment by KpwnZ** [comment]
I don't have iOS 14 device so sorry for that. :(

**Comment by Nexinity7** [comment]
I hope for iOS 14 support one day, thank you for the work you do for us 🙏
