### ISSUE TITLE
FaceID not working (Just pin code) and standard lockscreen

### ISSUE THREAD

**Issue by AppleMali90** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#8]
After I’ve installed the tweak Incant access the iPhone anymore with FaceID, but just with pin code and the display stays always on in the wrong way showing just the Notification Center with colors and notifications instead of the clock.

**Comment by AppleMali90** [comment]
I have iPhone X with 13.2.2

**Comment by ProfessorHicman** [comment]
Am also experience this issue on iPhone X on iOS 13.2.2
None of the features work at all while it stops FaceID working.

**Comment by KpwnZ** [comment]
Hi, sorry for the inconvenience. iOS 13 support in released versions is still in beta stage.

**Comment by KpwnZ** [comment]
I am working on a fix.

**Comment by bxkfng** [comment]
Same her. Thank you for Support!

**Comment by KpwnZ** [comment]
Already fixed, beta version will be available on my beta repo soon.

**Comment by KpwnZ** [comment]
It’s now available.
